/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simplebankingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import jdk.jfr.Timestamp;




public class MiniStatement extends javax.swing.JFrame {

   String cardNo; 
    
    public MiniStatement(String cardNo) {
        initComponents();
        
        this.cardNo = cardNo;
        String balance="";
        
          String lastNo="",firstNo= "";
          
          firstNo = cardNo.substring(0,4);
         
         char[] strca = cardNo.toCharArray();
         
         int size = strca.length;
         
         for(int i=size-1;i>size-5;i--)
         {
              lastNo = strca[i]+lastNo;
         }
         
        
        lbCardNo.setText("Card Number: "+firstNo+"-xxxx-xxxx-"+lastNo);
        
        
         
        
        String SUrl,SBank,SPass,query;
     
     SUrl= "jdbc:MySQL://localhost:3306/java_crud_db";
     SBank= "root";
     SPass="";  
     
     

     
     
      try
     {
         
           Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection(SUrl,SBank,SPass);
          java.sql.Statement st = con.createStatement(); 
          
              
              
              query = "SELECT * FROM statement WHERE cardNo="+cardNo;
              
              ResultSet rs = st.executeQuery(query);
              
              while(rs.next()){
                
                //  pinDB = rs.getString("pin");
                 
              
                  
                   String transaction = rs.getString("transactionType");
                   balance = String.valueOf(rs.getInt("balance"));
                   String amount = String.valueOf(rs.getInt("amount"));
                  
                   
                   String date = String.valueOf( rs.getTimestamp("date"));
                   
                   String tbData []= {date,transaction,amount};
                   
                   DefaultTableModel tblModel = (DefaultTableModel) tbTransactions.getModel();
                   
                   tblModel.addRow(tbData);
                   


                   
              
                  }
              
              lbBalance.setText("Your total balance is: R"+balance);
              
              
     }
                  
                   
                  
    
       catch(Exception e)
     {
        System.out.println("Error!"+e.getMessage());
     }
     
      
        
    }

    private MiniStatement() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbMyBank = new javax.swing.JLabel();
        btExitMini = new javax.swing.JButton();
        lbCardNo = new javax.swing.JLabel();
        lbTrans2 = new javax.swing.JLabel();
        lbTrans3 = new javax.swing.JLabel();
        lbBalance = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTransactions = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 700));

        lbMyBank.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbMyBank.setForeground(new java.awt.Color(255, 255, 255));
        lbMyBank.setText("My Bank");

        btExitMini.setBackground(new java.awt.Color(153, 153, 153));
        btExitMini.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btExitMini.setForeground(new java.awt.Color(255, 255, 255));
        btExitMini.setText("Exit");
        btExitMini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitMiniActionPerformed(evt);
            }
        });

        lbCardNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCardNo.setForeground(new java.awt.Color(255, 255, 255));
        lbCardNo.setText("Card Number:    5040 XXXX XXXX 3341");

        lbTrans2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTrans2.setForeground(new java.awt.Color(255, 255, 255));

        lbTrans3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTrans3.setForeground(new java.awt.Color(255, 255, 255));

        lbBalance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbBalance.setForeground(new java.awt.Color(255, 255, 255));
        lbBalance.setText("Your total Balance is R8 000");

        tbTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Transaction", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tbTransactions);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lbMyBank, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lbCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(393, 393, 393))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btExitMini, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29))))
                                .addGap(323, 323, 323)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTrans2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTrans3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbMyBank, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lbTrans2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTrans3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lbBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExitMini, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExitMiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitMiniActionPerformed
        Transaction TransactionFrame = new Transaction(cardNo);
        TransactionFrame.setVisible(true);
        TransactionFrame.pack();
        TransactionFrame.setLocationRelativeTo(null);//center
        this.dispose();
    }//GEN-LAST:event_btExitMiniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MiniStatement().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExitMini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBalance;
    private javax.swing.JLabel lbCardNo;
    private javax.swing.JLabel lbMyBank;
    private javax.swing.JLabel lbTrans2;
    private javax.swing.JLabel lbTrans3;
    private javax.swing.JTable tbTransactions;
    // End of variables declaration//GEN-END:variables
}
