
package simplebankingsystem;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class SignUpPg2 extends javax.swing.JFrame {
    
    String nm;
    String sm;
    String dob1;
    String ge;
    String em;
    String ma;
    String ad;
    String ci;
    String pr;
    String co;
    int fn;

  
    public SignUpPg2(String name,String surname,String dob,String gender,String email,String marital,String address,String city,String province,String code,int formNo)
    {
        initComponents();
        nm=name;
        sm=surname;
        dob1=dob;
        ge=gender;
        em=email;
        ma=marital;
        ad=address;
        ci=city;
        pr=province;
        co=code;
        fn=formNo;
       lbForm.setText("Form No: "+fn);

         
    }
    
    

    private SignUpPg2() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgExisting = new javax.swing.ButtonGroup();
        bgPensioner = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        LEFT = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        lbPage2 = new javax.swing.JLabel();
        lbReligion = new javax.swing.JLabel();
        lbCategory = new javax.swing.JLabel();
        lbIncome = new javax.swing.JLabel();
        lbEducation = new javax.swing.JLabel();
        lbOccupation = new javax.swing.JLabel();
        tfIDNo = new javax.swing.JTextField();
        lbIDNo = new javax.swing.JLabel();
        tbSars = new javax.swing.JTextField();
        lbSars = new javax.swing.JLabel();
        rbAccYes = new javax.swing.JRadioButton();
        rbAccNo = new javax.swing.JRadioButton();
        rbPenYes = new javax.swing.JRadioButton();
        rbPenNo = new javax.swing.JRadioButton();
        tbPerNo = new javax.swing.JTextField();
        lbPerNo = new javax.swing.JLabel();
        lbPen = new javax.swing.JLabel();
        lbExiAcc = new javax.swing.JLabel();
        btNextPg2 = new javax.swing.JButton();
        lbForm = new javax.swing.JLabel();
        cbReligion = new javax.swing.JComboBox<>();
        cbCategory = new javax.swing.JComboBox<>();
        cbIncome = new javax.swing.JComboBox<>();
        cbEducation = new javax.swing.JComboBox<>();
        cbOccopation = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Account Application Form Page 2");
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 800));
        jPanel1.setLayout(null);

        Left.setBackground(new java.awt.Color(255, 102, 51));
        Left.setPreferredSize(new java.awt.Dimension(450, 800));

        LEFT.setBackground(new java.awt.Color(255, 102, 51));
        LEFT.setPreferredSize(new java.awt.Dimension(450, 800));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bank.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel4.setFont(new java.awt.Font("Segoe Script", 2, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MY BANK");

        javax.swing.GroupLayout LEFTLayout = new javax.swing.GroupLayout(LEFT);
        LEFT.setLayout(LEFTLayout);
        LEFTLayout.setHorizontalGroup(
            LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LEFTLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LEFTLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LEFTLayout.setVerticalGroup(
            LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LEFTLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
            .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LEFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
            .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LEFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(Left);
        Left.setBounds(0, 0, 450, 800);

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setPreferredSize(new java.awt.Dimension(450, 800));

        lbPage2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPage2.setForeground(new java.awt.Color(255, 102, 51));
        lbPage2.setText("Page 2: Additional Details");

        lbReligion.setBackground(new java.awt.Color(153, 153, 153));
        lbReligion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbReligion.setForeground(new java.awt.Color(102, 102, 102));
        lbReligion.setText("Religion");

        lbCategory.setBackground(new java.awt.Color(153, 153, 153));
        lbCategory.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbCategory.setForeground(new java.awt.Color(102, 102, 102));
        lbCategory.setText("Category");

        lbIncome.setBackground(new java.awt.Color(153, 153, 153));
        lbIncome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbIncome.setForeground(new java.awt.Color(102, 102, 102));
        lbIncome.setText("Income");

        lbEducation.setBackground(new java.awt.Color(153, 153, 153));
        lbEducation.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbEducation.setForeground(new java.awt.Color(102, 102, 102));
        lbEducation.setText("Educational");

        lbOccupation.setBackground(new java.awt.Color(153, 153, 153));
        lbOccupation.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbOccupation.setForeground(new java.awt.Color(102, 102, 102));
        lbOccupation.setText("Occupation");

        tfIDNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfIDNo.setForeground(new java.awt.Color(102, 102, 102));
        tfIDNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDNoActionPerformed(evt);
            }
        });
        tfIDNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIDNoKeyTyped(evt);
            }
        });

        lbIDNo.setBackground(new java.awt.Color(153, 153, 153));
        lbIDNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbIDNo.setForeground(new java.awt.Color(102, 102, 102));
        lbIDNo.setText("ID No");

        tbSars.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbSars.setForeground(new java.awt.Color(102, 102, 102));
        tbSars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSarsActionPerformed(evt);
            }
        });
        tbSars.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbSarsKeyTyped(evt);
            }
        });

        lbSars.setBackground(new java.awt.Color(153, 153, 153));
        lbSars.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbSars.setForeground(new java.awt.Color(102, 102, 102));
        lbSars.setText("Sars No");

        rbAccYes.setBackground(new java.awt.Color(255, 255, 255));
        bgExisting.add(rbAccYes);
        rbAccYes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbAccYes.setText("Yes");
        rbAccYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAccYesActionPerformed(evt);
            }
        });

        rbAccNo.setBackground(new java.awt.Color(255, 255, 255));
        bgExisting.add(rbAccNo);
        rbAccNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbAccNo.setText("No");

        rbPenYes.setBackground(new java.awt.Color(255, 255, 255));
        bgPensioner.add(rbPenYes);
        rbPenYes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbPenYes.setForeground(new java.awt.Color(102, 102, 102));
        rbPenYes.setText("Yes");
        rbPenYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPenYesActionPerformed(evt);
            }
        });

        rbPenNo.setBackground(new java.awt.Color(255, 255, 255));
        bgPensioner.add(rbPenNo);
        rbPenNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbPenNo.setForeground(new java.awt.Color(102, 102, 102));
        rbPenNo.setText("No");
        rbPenNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPenNoActionPerformed(evt);
            }
        });

        tbPerNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbPerNo.setForeground(new java.awt.Color(102, 102, 102));
        tbPerNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbPerNoActionPerformed(evt);
            }
        });
        tbPerNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbPerNoKeyTyped(evt);
            }
        });

        lbPerNo.setBackground(new java.awt.Color(153, 153, 153));
        lbPerNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbPerNo.setForeground(new java.awt.Color(102, 102, 102));
        lbPerNo.setText("Persal No");

        lbPen.setBackground(new java.awt.Color(153, 153, 153));
        lbPen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbPen.setForeground(new java.awt.Color(102, 102, 102));
        lbPen.setText("Pensioner");

        lbExiAcc.setBackground(new java.awt.Color(153, 153, 153));
        lbExiAcc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbExiAcc.setForeground(new java.awt.Color(102, 102, 102));
        lbExiAcc.setText("Existing Account");

        btNextPg2.setBackground(new java.awt.Color(255, 102, 51));
        btNextPg2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btNextPg2.setForeground(new java.awt.Color(255, 255, 255));
        btNextPg2.setText("Next...");
        btNextPg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextPg2ActionPerformed(evt);
            }
        });

        lbForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbForm.setForeground(new java.awt.Color(255, 102, 51));
        lbForm.setText("Form No: 1111");

        cbReligion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbReligion.setForeground(new java.awt.Color(102, 102, 102));
        cbReligion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Christian", "Muslim", "Hindu", "Others", " " }));

        cbCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCategory.setForeground(new java.awt.Color(102, 102, 102));
        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "General", "Supervisor", "Management", "Others" }));

        cbIncome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbIncome.setForeground(new java.awt.Color(102, 102, 102));
        cbIncome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "<R1 500.00", "<R2 500.00", "<R5 000.00", "Up to R10 000.00", "Above R10 000.00" }));

        cbEducation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbEducation.setForeground(new java.awt.Color(102, 102, 102));
        cbEducation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non Graduate", "Graduate", "Post-Graduate", "Doctrate", "Others" }));

        cbOccopation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbOccopation.setForeground(new java.awt.Color(102, 102, 102));
        cbOccopation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employed", "Self-Employed", "Business", "Student", "Reired", "Others" }));

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbReligion)
                            .addComponent(lbIncome)
                            .addGroup(RightLayout.createSequentialGroup()
                                .addComponent(lbIDNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfIDNo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RightLayout.createSequentialGroup()
                                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbExiAcc)
                                            .addComponent(lbPen)
                                            .addComponent(lbPerNo)
                                            .addComponent(lbSars)
                                            .addComponent(lbOccupation))
                                        .addGap(18, 18, 18))
                                    .addGroup(RightLayout.createSequentialGroup()
                                        .addComponent(lbCategory)
                                        .addGap(69, 69, 69)))
                                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tbSars)
                                    .addComponent(tbPerNo)
                                    .addGroup(RightLayout.createSequentialGroup()
                                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbPenYes)
                                            .addComponent(rbAccYes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rbPenNo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btNextPg2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lbForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbReligion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbIncome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                                .addComponent(lbEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbOccopation, 0, 249, Short.MAX_VALUE)
                                    .addComponent(cbEducation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lbPage2)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPage2)
                .addGap(18, 18, 18)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbReligion)
                    .addComponent(cbReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategory)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIncome)
                    .addComponent(cbIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOccupation)
                    .addComponent(cbOccopation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIDNo)
                    .addComponent(tfIDNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSars)
                    .addComponent(tbSars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPerNo)
                    .addComponent(tbPerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPen)
                    .addComponent(rbPenNo)
                    .addComponent(rbPenYes))
                .addGap(26, 26, 26)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbExiAcc)
                    .addComponent(rbAccYes)
                    .addComponent(rbAccNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btNextPg2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel1.add(Right);
        Right.setBounds(450, 0, 450, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIDNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDNoActionPerformed

    private void tbSarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSarsActionPerformed

    private void rbAccYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAccYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAccYesActionPerformed

    private void rbPenYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPenYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPenYesActionPerformed

    private void rbPenNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPenNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPenNoActionPerformed

    private void tbPerNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbPerNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbPerNoActionPerformed

    private void btNextPg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextPg2ActionPerformed

        
     String name, surname ,dob,gender, email, maritalStatus,address,city,province,code;
    
    //Details page 2
     String religion,category, income, education,occupation, sarsNo,persalNo,pensioner, existingAcc;
             int idNo;
             
     
     String SUrl,SCustomer,SPass,query;
     
     SUrl= "jdbc:MySQL://localhost:3306/java_crud_db";
     SCustomer ="root";
     SPass=""; 
     try
     {
         
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection(SUrl,SCustomer,SPass);
          Statement st = con.createStatement();
          
          if("".equals(tfIDNo.getText()) )
          {
            JOptionPane.showMessageDialog(new JFrame(),"ID No is required", "Error",JOptionPane.ERROR_MESSAGE);
         
          }
          else if("".equals(tbSars.getText()))
          {
              JOptionPane.showMessageDialog(new JFrame(),"Sars No is required.If Not ", "Error",JOptionPane.ERROR_MESSAGE);
          }
             else if("".equals(tbPerNo.getText()))
          {
              JOptionPane.showMessageDialog(new JFrame(),"Persal No is required.If Not ", "Error",JOptionPane.ERROR_MESSAGE);
          }
                else if(!(rbPenYes.isSelected() || rbPenNo.isSelected()) )
          {
              JOptionPane.showMessageDialog(new JFrame(),"Select yes if your are a pensioner and no if you are not", "Error",JOptionPane.ERROR_MESSAGE);
          }
                   else if(!(rbAccYes.isSelected() || rbAccNo.isSelected()) )
          {
              JOptionPane.showMessageDialog(new JFrame(),"Select yes if you already have an account and no if you dont have an account", "Error",JOptionPane.ERROR_MESSAGE);
          }
          else
          {
              
              if(rbAccYes.isSelected())
              {
                      JOptionPane.showMessageDialog(new JFrame(),"Already have an account please login", "Error",JOptionPane.ERROR_MESSAGE);
                       Login LoginFrame = new Login("");
        LoginFrame.setVisible(true);
       LoginFrame.pack();
       LoginFrame.setLocationRelativeTo(null);//center
        this.dispose();
              }
              else
              {
                  
                  name=nm;surname = sm;dob = dob1;gender= ge ;email=em;maritalStatus=ma;address=ad;city=ci;province=pr;code=co;
                  religion= cbReligion.getSelectedItem().toString();
                  category =cbCategory.getSelectedItem().toString();
                  income = cbIncome.getSelectedItem().toString();
                  education=cbEducation.getSelectedItem().toString();
                  occupation=cbOccopation.getSelectedItem().toString();
                  idNo = Integer.parseInt( tfIDNo.getText());
                  sarsNo = tbSars.getText();
                  persalNo =tbPerNo.getText();           
                  if(rbPenYes.isSelected())
                  {
                    pensioner="Yes";
                  }
                  else
                  {
                      pensioner="No";
                  }
                  existingAcc ="No";
                  
                  Customer customer = new Customer(name, surname, dob, gender, email, maritalStatus,address, city, province, code, religion , category, income, education,
                  occupation, idNo, sarsNo, persalNo, pensioner, existingAcc,fn);
           
                 /* query = "INSERT INTO customer(name, surname, dob, gender, email, maritalStatus, "
                          + "address, city, province, code, religion , category, income, education,"
                          + " occupation, idNo, sarsNo, persalNo, pensioner, existingAcc)"
                          +"values('"+name+"', '"+surname+"', '"+dob+"', '"+gender+"', '"+email+"', '"+maritalStatus+"', '"+address
                          +"', '"+city+"', '"+province+"', '"+code+"', '"+religion+"', '"+category+"', '"+income+"', '"+education+"', '"+
                          occupation+"', '"+idNo+"', '"+sarsNo+"', '"+persalNo+"', '"+pensioner+"', '"+existingAcc+"')";
                  */
                 
                 query = "INSERT INTO customer(name, surname, dob, gender, email, maritalStatus, "
                          + "address, city, province, code, religion , category, income, education,"
                          + " occupation, idNo, sarsNo, persalNo, pensioner, existingAcc, FormNo)"
                          +"values('"+customer.getName()+"', '"+customer.getSurname()+"', '"+customer.getDob()+"', '"+customer.getGender()+"', '"+customer.getEmail()
                         +"', '"+customer.getMaritalStatus()+"', '"+customer.getAddress()+"', '"+customer.getCity()+"', '"+customer.getProvince()+"', '"+customer.getCode()
                         +"', '"+customer.getReligion()+"', '"+customer.getCategory()+"', '"+customer.getIncome()+"', '"+customer.getEducation()+"', '"+
                          customer.getOccupation()+"', '"+customer.getIdNo()+"', '"+customer.getSarsNo()+"', '"+customer.getPersalNo()+"', '"+customer.getPensioner()+"', "
                         + "'"+customer.getExistingAcc()+"', '"+customer.getFormNo()+"')";
                  
                  
                  
                  
                  st.execute(query);
                  
                  
                  SignUpPg3 SignUpPg3Frame = new SignUpPg3(fn,idNo);
                  SignUpPg3Frame.setVisible(true);
                  SignUpPg3Frame.pack();
                  SignUpPg3Frame.setLocationRelativeTo(null);//center
                   this.dispose();
              
              }
              
          }
          
           
           
           
     }catch(Exception e)
     {
        System.out.println("Error!"+e.getMessage());
     }
        
        
    //String religion = cbReligion.;
    // String category = cbCategory;
      //String income=cbIncome;
    //String education = cbEducation;
    //String occupation =cbOccopation ;
    //int idNo = Integer.parseInt( tfIDNo.getText());
 //   int sarsNo= Integer.parseInt( tbSars.getText());
   // int persalNo= Integer.parseInt( tbPerNo.getText());
  //  Boolean pensioner=bgPensioner;
   // Boolean existingAcc=bgExisting;
   
   
   
   
    
       // SignUp details = new SignUp();
        
       
    
    
    
       //  Customer newCustomer = new Customer();
            
       
       

    }//GEN-LAST:event_btNextPg2ActionPerformed

    private void tfIDNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIDNoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_tfIDNoKeyTyped

    private void tbSarsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbSarsKeyTyped
        
        char c = evt.getKeyChar();
        // TODO add your handling code here:
         if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbSarsKeyTyped

    private void tbPerNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPerNoKeyTyped
        // TODO add your handling code here:
        
         char c = evt.getKeyChar();
         if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbPerNoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignUpPg2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LEFT;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.ButtonGroup bgExisting;
    private javax.swing.ButtonGroup bgPensioner;
    private javax.swing.JButton btNextPg2;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JComboBox<String> cbEducation;
    private javax.swing.JComboBox<String> cbIncome;
    private javax.swing.JComboBox<String> cbOccopation;
    private javax.swing.JComboBox<String> cbReligion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCategory;
    private javax.swing.JLabel lbEducation;
    private javax.swing.JLabel lbExiAcc;
    private javax.swing.JLabel lbForm;
    private javax.swing.JLabel lbIDNo;
    private javax.swing.JLabel lbIncome;
    private javax.swing.JLabel lbOccupation;
    private javax.swing.JLabel lbPage2;
    private javax.swing.JLabel lbPen;
    private javax.swing.JLabel lbPerNo;
    private javax.swing.JLabel lbReligion;
    private javax.swing.JLabel lbSars;
    private javax.swing.JRadioButton rbAccNo;
    private javax.swing.JRadioButton rbAccYes;
    private javax.swing.JRadioButton rbPenNo;
    private javax.swing.JRadioButton rbPenYes;
    private javax.swing.JTextField tbPerNo;
    private javax.swing.JTextField tbSars;
    private javax.swing.JTextField tfIDNo;
    // End of variables declaration//GEN-END:variables
}
