/*
 * 
 */
package simplebankingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SuperiorAuto
 */
public class SignUpPg3 extends javax.swing.JFrame {

   String cardNo="",random1,random2,pin;
    
    
    int formNo,idNo;
    
    SignUpPg3(int FormNo,int IdNo) {
        initComponents();
        formNo = FormNo;
        this.idNo = IdNo;
         lbForm.setText("Form No: "+formNo);
         
         Random random = new Random();
         
           
              random1=""+random.nextInt(9)+""+random.nextInt(9)+""+random.nextInt(9)+""+random.nextInt(9);
              random2=""+random.nextInt(9)+""+random.nextInt(9)+""+random.nextInt(9)+""+random.nextInt(9);
              pin =""+random.nextInt(9)+""+random.nextInt(9)+""+random.nextInt(9)+""+random.nextInt(9);
         
         
       
         
         cardNo =cardNo+""+ "52849734"+""+random1+""+""+random2;
         
         String lastNo="" ;
         
         char[] strca = cardNo.toCharArray();
         
         int size = strca.length;
         
         for(int i=size-1;i>size-5;i--)
         {
              lastNo = strca[i]+lastNo;
         }
         
         
         lbPrivateCardNo.setText("XXXX-XXXX-XXXX-"+lastNo);
    }
     
    
    

    private SignUpPg3() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAccType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        LEFT = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        lbPage2 = new javax.swing.JLabel();
        lbAccType = new javax.swing.JLabel();
        lbCardNo = new javax.swing.JLabel();
        lbPrivateCardNo = new javax.swing.JLabel();
        lbCardDisclaimer = new javax.swing.JLabel();
        lbPIN = new javax.swing.JLabel();
        lbPinNo = new javax.swing.JLabel();
        lbPinDisclaimer = new javax.swing.JLabel();
        lbServices = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        lbForm = new javax.swing.JLabel();
        rbSavings = new javax.swing.JRadioButton();
        rbFixed = new javax.swing.JRadioButton();
        rbCurrent = new javax.swing.JRadioButton();
        rbRecurring = new javax.swing.JRadioButton();
        cbATM = new javax.swing.JCheckBox();
        cbInternet = new javax.swing.JCheckBox();
        cbMobile = new javax.swing.JCheckBox();
        cbEmail = new javax.swing.JCheckBox();
        cbCheque = new javax.swing.JCheckBox();
        cbEStatement = new javax.swing.JCheckBox();
        cbDeclaration = new javax.swing.JCheckBox();
        btSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Account Application Form Page 3");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));
        jPanel1.setLayout(null);

        Left.setBackground(new java.awt.Color(255, 102, 51));

        LEFT.setBackground(new java.awt.Color(255, 102, 51));
        LEFT.setPreferredSize(new java.awt.Dimension(450, 700));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bank.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel4.setFont(new java.awt.Font("Segoe Script", 2, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MY BANK");

        javax.swing.GroupLayout LEFTLayout = new javax.swing.GroupLayout(LEFT);
        LEFT.setLayout(LEFTLayout);
        LEFTLayout.setHorizontalGroup(
            LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LEFTLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LEFTLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LEFTLayout.setVerticalGroup(
            LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LEFTLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeftLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LEFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeftLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LEFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(Left);
        Left.setBounds(0, 0, 450, 700);

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setMinimumSize(new java.awt.Dimension(450, 700));
        Right.setPreferredSize(new java.awt.Dimension(450, 700));

        lbPage2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPage2.setForeground(new java.awt.Color(255, 102, 51));
        lbPage2.setText("Page 3: Account Details");

        lbAccType.setBackground(new java.awt.Color(153, 153, 153));
        lbAccType.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbAccType.setForeground(new java.awt.Color(102, 102, 102));
        lbAccType.setText("Account Type:");

        lbCardNo.setBackground(new java.awt.Color(153, 153, 153));
        lbCardNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbCardNo.setForeground(new java.awt.Color(102, 102, 102));
        lbCardNo.setText("Card Number:");

        lbPrivateCardNo.setBackground(new java.awt.Color(153, 153, 153));
        lbPrivateCardNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbPrivateCardNo.setForeground(new java.awt.Color(102, 102, 102));
        lbPrivateCardNo.setText("XXXX-XXXX-XXXX-4184");

        lbCardDisclaimer.setBackground(new java.awt.Color(153, 153, 153));
        lbCardDisclaimer.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        lbCardDisclaimer.setForeground(new java.awt.Color(102, 102, 102));
        lbCardDisclaimer.setText("(Your 16-degit Card Number)                    It would appear on ATM Card/Cheque Book and Statements");

        lbPIN.setBackground(new java.awt.Color(153, 153, 153));
        lbPIN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbPIN.setForeground(new java.awt.Color(102, 102, 102));
        lbPIN.setText("PIN:");

        lbPinNo.setBackground(new java.awt.Color(153, 153, 153));
        lbPinNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbPinNo.setForeground(new java.awt.Color(102, 102, 102));
        lbPinNo.setText("XXXX");

        lbPinDisclaimer.setBackground(new java.awt.Color(153, 153, 153));
        lbPinDisclaimer.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        lbPinDisclaimer.setForeground(new java.awt.Color(102, 102, 102));
        lbPinDisclaimer.setText("(4-digit password)");

        lbServices.setBackground(new java.awt.Color(153, 153, 153));
        lbServices.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbServices.setForeground(new java.awt.Color(102, 102, 102));
        lbServices.setText("Services Required:");

        btCancel.setBackground(new java.awt.Color(255, 102, 51));
        btCancel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btCancel.setForeground(new java.awt.Color(255, 255, 255));
        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lbForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbForm.setForeground(new java.awt.Color(255, 102, 51));
        lbForm.setText("Form No: 1111");

        rbSavings.setBackground(new java.awt.Color(255, 255, 255));
        bgAccType.add(rbSavings);
        rbSavings.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbSavings.setForeground(new java.awt.Color(102, 102, 102));
        rbSavings.setText("Savings Account");
        rbSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSavingsActionPerformed(evt);
            }
        });

        rbFixed.setBackground(new java.awt.Color(255, 255, 255));
        bgAccType.add(rbFixed);
        rbFixed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbFixed.setForeground(new java.awt.Color(102, 102, 102));
        rbFixed.setText("Fixed Deposit Account");

        rbCurrent.setBackground(new java.awt.Color(255, 255, 255));
        bgAccType.add(rbCurrent);
        rbCurrent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbCurrent.setForeground(new java.awt.Color(153, 153, 153));
        rbCurrent.setText("Current Account");
        rbCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCurrentActionPerformed(evt);
            }
        });

        rbRecurring.setBackground(new java.awt.Color(255, 255, 255));
        bgAccType.add(rbRecurring);
        rbRecurring.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbRecurring.setForeground(new java.awt.Color(102, 102, 102));
        rbRecurring.setText("Recurring Deposit Account ");

        cbATM.setBackground(new java.awt.Color(255, 255, 255));
        cbATM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbATM.setForeground(new java.awt.Color(102, 102, 102));
        cbATM.setText("ATM Card");

        cbInternet.setBackground(new java.awt.Color(255, 255, 255));
        cbInternet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbInternet.setForeground(new java.awt.Color(102, 102, 102));
        cbInternet.setText("Internet Banking");

        cbMobile.setBackground(new java.awt.Color(255, 255, 255));
        cbMobile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMobile.setForeground(new java.awt.Color(102, 102, 102));
        cbMobile.setText("Mobile Banking");

        cbEmail.setBackground(new java.awt.Color(255, 255, 255));
        cbEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbEmail.setForeground(new java.awt.Color(102, 102, 102));
        cbEmail.setText("EMAIL alerts");

        cbCheque.setBackground(new java.awt.Color(255, 255, 255));
        cbCheque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCheque.setForeground(new java.awt.Color(102, 102, 102));
        cbCheque.setText("Cheque Book");

        cbEStatement.setBackground(new java.awt.Color(255, 255, 255));
        cbEStatement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbEStatement.setForeground(new java.awt.Color(102, 102, 102));
        cbEStatement.setText("E-Statement");

        cbDeclaration.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        cbDeclaration.setForeground(new java.awt.Color(102, 102, 102));
        cbDeclaration.setText("I hereby declare that the entered details correct to the best of my knowledge");

        btSubmit.setBackground(new java.awt.Color(255, 102, 51));
        btSubmit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btSubmit.setText("Submit");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbPrivateCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addComponent(lbPinNo)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lbPage2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAccType)
                            .addGroup(RightLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbForm, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RightLayout.createSequentialGroup()
                                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbSavings)
                                            .addComponent(rbCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbRecurring)
                                            .addComponent(rbFixed, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(RightLayout.createSequentialGroup()
                            .addComponent(btSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                            .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34))
                        .addGroup(RightLayout.createSequentialGroup()
                            .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbServices)
                                .addComponent(lbPinDisclaimer)
                                .addComponent(lbPIN)
                                .addComponent(lbCardDisclaimer, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(RightLayout.createSequentialGroup()
                                    .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbATM, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbEStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(cbDeclaration))
                            .addContainerGap()))))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPage2)
                .addGap(18, 18, 18)
                .addComponent(lbAccType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSavings)
                    .addComponent(rbFixed))
                .addGap(28, 28, 28)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCurrent)
                    .addComponent(rbRecurring))
                .addGap(38, 38, 38)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrivateCardNo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCardNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCardDisclaimer)
                .addGap(26, 26, 26)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPIN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPinNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPinDisclaimer)
                .addGap(18, 18, 18)
                .addComponent(lbServices)
                .addGap(18, 18, 18)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbATM)
                    .addComponent(cbInternet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMobile)
                    .addComponent(cbEmail))
                .addGap(12, 12, 12)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCheque)
                    .addComponent(cbEStatement))
                .addGap(20, 20, 20)
                .addComponent(cbDeclaration)
                .addGap(12, 12, 12)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jPanel1.add(Right);
        Right.setBounds(450, 0, 420, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSavingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSavingsActionPerformed

    private void rbCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCurrentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCurrentActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed

               String SUrl,SBank,SPass,query;
     
     SUrl= "jdbc:MySQL://localhost:3306/java_crud_db";
     SBank= "root";
     SPass="";  
     
        try
     {
         
           Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection(SUrl,SBank,SPass);
          java.sql.Statement st = con.createStatement(); 
          
              
              
                query = "DELETE FROM customer WHERE idNo="+idNo;
              
             // ResultSet rs = st.executeQuery(query);
                  
                               st.execute(query);
                               
                               
                               JOptionPane.showMessageDialog(new JFrame(),"Deleted");
             
                     Login LoginFrame = new Login("");
                     LoginFrame.setVisible(true);
                     LoginFrame.pack();
                      LoginFrame.setLocationRelativeTo(null);//center
                    this.dispose();
                             
                             
                         
                       
                  
                  
                  }
 
       catch(Exception e)
     {
        System.out.println("Error!"+e.getMessage());
     }
     
        
       
    }//GEN-LAST:event_btCancelActionPerformed

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        
        String cardNo,pin;
        
        int idNo ;
       
        String accountType="", declaration="",atmCard="",internet="",mobile="",email="",cheque="",statement="";
        
          String SUrl,SBank,SPass,query;
     
     SUrl= "jdbc:MySQL://localhost:3306/java_crud_db";
     SBank= "root";
     SPass="";  
     
     
     try
     {
         
           Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection(SUrl,SBank,SPass);
          Statement st = con.createStatement();
           if(!(rbSavings.isSelected() || rbFixed.isSelected() || rbCurrent.isSelected() || rbRecurring.isSelected() ) )
          {
            JOptionPane.showMessageDialog(new JFrame(),"Please select account type", "Error",JOptionPane.ERROR_MESSAGE);
         
          }
          else if(!(cbATM.isSelected() ||cbInternet.isSelected() || cbMobile.isSelected() || cbEmail.isSelected() || cbCheque.isSelected()||cbEStatement.isSelected() ))
          {
              JOptionPane.showMessageDialog(new JFrame(),"Please select atleast 1 or more service ", "Error",JOptionPane.ERROR_MESSAGE);
          }
            else if(!(cbDeclaration.isSelected() ))
          {
              JOptionPane.showMessageDialog(new JFrame(),"Please accept declaration ", "Error",JOptionPane.ERROR_MESSAGE);
          }
           else
          {
              
              
              cardNo = this.cardNo;
              pin = this.pin;
              idNo = this.idNo;
              
              if(rbSavings.isSelected() )
              {
                 accountType="Savings Account";
              
              }
              else if(rbFixed.isSelected())
              {
                 accountType="Fixed Deposit";
              }
              else if( rbCurrent.isSelected())
              {        
                   accountType="Current Account";
             }
              else
             {
                 accountType="Recurring Deposit";
                      
             }
              
              if(cbATM.isSelected() || cbInternet.isSelected() ||  cbMobile.isSelected() || cbEmail.isSelected() || cbCheque.isSelected() || cbEStatement.isSelected())
              {
                 
                    if(cbATM.isSelected())
                    {
                      atmCard="Yes";
                    }
                    else
                    {
                      atmCard="No";
                    }
                    
                    if(cbInternet.isSelected())
                    {
                       internet ="Yes";
                    }
                    else
                    {
                       internet ="No";
                    }
                  
                    if(cbMobile.isSelected())
                    {
                       mobile ="Yes";
                    }
                    else
                    {
                       mobile ="No";
                    }
                    if(cbEmail.isSelected())
                    {
                       email ="Yes";
                    }
                    else
                    {
                       email ="No";
                    }
                     if(cbCheque.isSelected())
                    {
                       cheque ="Yes";
                    }
                    else
                    {
                       
                        cheque="No";
                 
                    }
                        if(cbEStatement.isSelected())
                    {
                      statement="Yes";
                    }
                    else
                    {
                       
                        statement="No";
                 
                    }
                 
                 
                
                
                 
              }
            
              
              
              if(cbDeclaration.isSelected())
              {
                declaration ="Yes";

              }
              
              BankAccount account = new BankAccount(idNo,cardNo,pin, accountType,declaration, atmCard, internet, mobile,email, cheque, statement);
            
              
                query = "INSERT INTO bankaccount(idNo, cardNo, pin, accountType, declaration, atmCard, internet, mobile, email, cheque, statement)"+
                        "VALUES('"+ account.getIdNo()+"', '"+ account.getCardNo()+"', '"+account.getPin()+"', '"+account.getAccountType()+"', '"+
                        account.getDeclaration()+"', '"+account.getAtmCard()+"', '"+account.getInternet()+"', '"+account.getMobile()
                        +"', '"+account.getEmail()+"', '"+account.getCheque()+"', '"+account.getStatement() +"')";
                
                
                st.execute(query);
                        
                            
              
             
              JOptionPane.showMessageDialog(new JFrame(),"Account Created successfully!!\nCard No :"+account.cardNo+"\n"+"Pin:"+account.pin);
              
        
              FirstDeposit FirstDepositFrame= new FirstDeposit(account.cardNo);
              FirstDepositFrame.setVisible(true);
              FirstDepositFrame.pack();
              FirstDepositFrame.setLocationRelativeTo(null);//center
               this.dispose();
          } 
     }
     catch(Exception e)
     {
        System.out.println("Error!"+e.getMessage());
     }
    }//GEN-LAST:event_btSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignUpPg3().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LEFT;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.ButtonGroup bgAccType;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSubmit;
    private javax.swing.JCheckBox cbATM;
    private javax.swing.JCheckBox cbCheque;
    private javax.swing.JCheckBox cbDeclaration;
    private javax.swing.JCheckBox cbEStatement;
    private javax.swing.JCheckBox cbEmail;
    private javax.swing.JCheckBox cbInternet;
    private javax.swing.JCheckBox cbMobile;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAccType;
    private javax.swing.JLabel lbCardDisclaimer;
    private javax.swing.JLabel lbCardNo;
    private javax.swing.JLabel lbForm;
    private javax.swing.JLabel lbPIN;
    private javax.swing.JLabel lbPage2;
    private javax.swing.JLabel lbPinDisclaimer;
    private javax.swing.JLabel lbPinNo;
    private javax.swing.JLabel lbPrivateCardNo;
    private javax.swing.JLabel lbServices;
    private javax.swing.JRadioButton rbCurrent;
    private javax.swing.JRadioButton rbFixed;
    private javax.swing.JRadioButton rbRecurring;
    private javax.swing.JRadioButton rbSavings;
    // End of variables declaration//GEN-END:variables
}
