

package simplebankingsystem;



/**
 *
 * @author Tshabalala MG
 */
public class Transaction extends javax.swing.JFrame {

    
     String cardNo;
    
 
    
    
   
    public Transaction(String cardNo) {
        
          
        initComponents();
        
        this.cardNo=cardNo;
         
        
        
        
        
       
       
    }

    private Transaction() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btWithdrawal = new javax.swing.JButton();
        btMiniState = new javax.swing.JButton();
        btFastCash = new javax.swing.JButton();
        btChangePin = new javax.swing.JButton();
        btBalance = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btDeposit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selct Transaction");
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please Select your Transaction");

        btWithdrawal.setBackground(new java.awt.Color(153, 153, 153));
        btWithdrawal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btWithdrawal.setForeground(new java.awt.Color(255, 255, 255));
        btWithdrawal.setText("Cash Withdrawal");
        btWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWithdrawalActionPerformed(evt);
            }
        });

        btMiniState.setBackground(new java.awt.Color(153, 153, 153));
        btMiniState.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btMiniState.setForeground(new java.awt.Color(255, 255, 255));
        btMiniState.setText("Mini Statement");
        btMiniState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMiniStateActionPerformed(evt);
            }
        });

        btFastCash.setBackground(new java.awt.Color(153, 153, 153));
        btFastCash.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btFastCash.setForeground(new java.awt.Color(255, 255, 255));
        btFastCash.setText("Fast Cash");
        btFastCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFastCashActionPerformed(evt);
            }
        });

        btChangePin.setBackground(new java.awt.Color(153, 153, 153));
        btChangePin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btChangePin.setForeground(new java.awt.Color(255, 255, 255));
        btChangePin.setText("Change PIN");
        btChangePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangePinActionPerformed(evt);
            }
        });

        btBalance.setBackground(new java.awt.Color(153, 153, 153));
        btBalance.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btBalance.setForeground(new java.awt.Color(255, 255, 255));
        btBalance.setText("Balance Enquiry");
        btBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBalanceActionPerformed(evt);
            }
        });

        btExit.setBackground(new java.awt.Color(153, 153, 153));
        btExit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        btDeposit.setBackground(new java.awt.Color(153, 153, 153));
        btDeposit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btDeposit.setForeground(new java.awt.Color(255, 255, 255));
        btDeposit.setText("Deposit");
        btDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btFastCash, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btChangePin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btWithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMiniState, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btWithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMiniState, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFastCash, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btChangePin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWithdrawalActionPerformed
         Withdrawal  WithdrawalFrame = new Withdrawal(cardNo);
        WithdrawalFrame.setVisible(true);
       WithdrawalFrame.pack();
       WithdrawalFrame.setLocationRelativeTo(null);//center
        this.dispose();
    }//GEN-LAST:event_btWithdrawalActionPerformed

    private void btMiniStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMiniStateActionPerformed
        MiniStatement  MiniStatementFrame = new MiniStatement(cardNo);
       MiniStatementFrame.setVisible(true);
      MiniStatementFrame.pack();
      MiniStatementFrame.setLocationRelativeTo(null);//center
        this.dispose();
    }//GEN-LAST:event_btMiniStateActionPerformed

    private void btFastCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFastCashActionPerformed

        FastCash FastCashFrame = new FastCash(cardNo);
        FastCashFrame.setVisible(true);
        FastCashFrame.pack();
        FastCashFrame.setLocationRelativeTo(null);
        this.dispose();
        
        
   
    }//GEN-LAST:event_btFastCashActionPerformed

    private void btChangePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangePinActionPerformed
         ChangePin ChangePinFrame = new ChangePin (cardNo);
      ChangePinFrame.setVisible(true);
       ChangePinFrame.pack();
        ChangePinFrame.setLocationRelativeTo(null);//center
        this.dispose();
    }//GEN-LAST:event_btChangePinActionPerformed

    private void btBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBalanceActionPerformed
        Balance BalanceFrame = new Balance(cardNo);
        BalanceFrame.setVisible(true);
       BalanceFrame.pack();
      BalanceFrame.setLocationRelativeTo(null);//center
        this.dispose();
    }//GEN-LAST:event_btBalanceActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
         Login LoginFrame = new Login("");
        LoginFrame.setVisible(true);
       LoginFrame.pack();
       LoginFrame.setLocationRelativeTo(null);//center
        this.dispose();
                     
    }//GEN-LAST:event_btExitActionPerformed

    private void btDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositActionPerformed
        
        
        
        
        Deposit DepositFrame = new Deposit(cardNo);
        DepositFrame.setVisible(true);
       DepositFrame.pack();
       DepositFrame.setLocationRelativeTo(null);//center
        this.dispose();
    }//GEN-LAST:event_btDepositActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Transaction().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBalance;
    private javax.swing.JButton btChangePin;
    private javax.swing.JButton btDeposit;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btFastCash;
    private javax.swing.JButton btMiniState;
    private javax.swing.JButton btWithdrawal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
